{
 "title": "frontend-microservice - Metrics & Logs",
 "tags": [
  "microservices",
  "frontend-microservice",
  "devsecops"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "frontend-microservice — CPU (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"microservices\", pod=~\"frontend-microservice.*\", container!=\"\", container!=\"POD\"}[5m])) by (pod) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "frontend-microservice — RAM (MB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "megabytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"microservices\", pod=~\"frontend-microservice.*\", container!=\"\", container!=\"POD\"}) by (pod) / 1024 / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "frontend-microservice — Requetes Nginx (/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total{namespace=\"microservices\", app=\"frontend-microservice\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "frontend-microservice — Logs erreurs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({namespace=\"microservices\", pod=~\"frontend-microservice.*\"} |~ \"error|failed| 502 | 503 | 504 \" [5m])"
    }
   ]
  },
  {
   "title": "frontend-microservice — Alerte: Nginx down (health)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{namespace=\"microservices\", app=\"frontend-microservice\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "frontend-microservice — Connexions actives (Reading/Writing/Waiting)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_connections_reading{namespace=\"microservices\", app=\"frontend-microservice\"}",
     "legendFormat": "Reading"
    },
    {
     "expr": "nginx_connections_writing{namespace=\"microservices\", app=\"frontend-microservice\"}",
     "legendFormat": "Writing"
    },
    {
     "expr": "nginx_connections_waiting{namespace=\"microservices\", app=\"frontend-microservice\"}",
     "legendFormat": "Waiting"
    }
   ]
  }
 ]
}